version: "3.8"

services:
  mongodb:
    image: mongo
    container_name: campusfit_db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=campusfit_user
      - MONGO_INITDB_ROOT_PASSWORD=campusfit_password
      - MONGO_INITDB_DATABASE=campusfit_db
    networks:
      - campusfit_network

    restart:  unless-stopped

  app:
    build: .
    container_name: campusfit_main
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - APP_ENV=development
      - MONGO_URI=mongodb://campusfit_user:campusfit_password@mongodb:27017/campusfit_db?authSource=admin
    depends_on:
      - mongodb
    networks:
      - campusfit_network
    restart: unless-stopped

volumes:
  mongo_data:

networks:
  campusfit_network:
    driver: bridge
  